apiVersion: v1
kind: Service
metadata:
  name: nginx-external-ip
spec:
  selector:
    app: my-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 80.11.12.10