apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    name: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine   # nginx:1.19.6
    resources:
    ports:
      - containerPort: 80
