apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    name: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    
    # When should a container restart:
    # check page in /usr/share/nginx/html/index.html
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1

    # When should a container start receiving traffic:
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 5
    resources:
    ports:
      - containerPort: 80
